name: Lint & test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - name: Install shellcheck
      run: |
        sudo apt-get -qq update
        sudo apt-get -qq install shellcheck
    - name: Checkout the project
      uses: actions/checkout@v2
    - name: Lint with shellcheck
      run: |
        echo "::add-matcher::.github/shellcheck.json"
        cd bin
        shellcheck -x homeshick
        echo "::remove-matcher owner=shellcheck::"

  test:
    strategy:
      matrix:
        bash-version: ['3.2', '3.2.48', '3.2.57', '4.0', '4.1', '4.2', '4.3', '4.3.30', '4.4', '5.0']

    runs-on: ubuntu-latest
    steps:
    - name: Install testing dependencies
      run: |
        sudo apt-add-repository ppa:fish-shell/release-2 --yes
        sudo apt-get -qq update
        sudo apt-get -qq install fish expect tcsh
        git clone https://github.com/sstephenson/bats.git /tmp/bats
        mkdir -p /tmp/local
        bash /tmp/bats/install.sh /tmp/local
    - name: Checkout the project
      uses: actions/checkout@v2
    - name: Cache bash versions
      uses: actions/cache@v2
      env:
        cache-name: bash-version
      with:
        path: test/bash-versions/${{ matrix.bash-version }}
        key: ${{ env.cache-name }}-${{ matrix.bash-version }}
    - name: Download & compile bash ${{ matrix.bash-version }}
      run: test/get_bash.sh "${{ matrix.bash-version }}"
    - name: Test
      run: test/bash-versions/bash-${{ matrix.bash-version }}/bash /tmp/local/bin/bats --tap test/suites
